# @package _group_
logging_level: INFO
params:
  gpus: 4
  max_epochs: ${training.epochs}
  log_every_n_steps: 20
  check_val_every_n_epoch: 1
  flush_logs_every_n_steps: 100
  weights_summary: null
  deterministic: False
  benchmark: True
  profiler: "simple"
  distributed_backend: "ddp"
